### ISSUE TITLE
ZCL_ALOG_DBTAB_LOGGER Contains syntax error

### ISSUE THREAD

**Issue by antelio** [flaiker/abap-log#41]
I've just clone repos and activate.
Class ZCL_ALOG_DBTAB_LOGGER is returning syntax error.

Still searching for details on source code.

Following System version (IDES ECC6-EHP7)
SAP_BASIS	740	0009	SAPKB74009	SAP Basis Component
SAP_ABA	740	0009	SAPKA74009	Cross-Application Component

**Comment by flaiker** [comment]
Any hint on which line the issue is in? I just reinstalled the repo on 750SP2 and 751SP2, both worked fine. Unfortunately I don't have a 740 SP9 system at hand and I cannot see anything _by eye_ that needs to be downported.

**Comment by flaiker** [comment]
Were you able to resolve the issue or identify the problematic statement?

**Comment by flaiker** [comment]
Fixed in #49
