### ISSUE TITLE
zalog_example_static_logger dumps on execution

### ISSUE THREAD

**Issue by arcanist123** [flaiker/abap-log#53]
Hello.
Simple issue - the program zalog_example_static_logger dumps when I try to execute it. Is it expected? Dump attached
[test.txt](https://github.com/flaiker/abap-log/files/3244746/test.txt)

**Comment by flaiker** [comment]
Hi, thanks for raising the issue.

Seems to be this check for T100 support, in regards to the internal table logger.
https://github.com/flaiker/abap-log/blob/cb17228a3a5a663bf5683bfa3bf5d5e1a3f7d76d/src/zcl_alog_static_configuration.clas.abap#L90-L95

I'll adjust some things.

**Comment by flaiker** [comment]
@arcanist123 Can you check again with the latest version?

**Comment by arcanist123** [comment]
Hello.

Seems to be working fine now.

Thanks
